DROP TABLE IF EXISTS CLIENTE;

CREATE TABLE CLIENTE (
    id INTEGER NOT NULL AUTO_INCREMENT,
    nome VARCHAR(128) NOT NULL,
    data_nascimento VARCHAR(128) NOT NULL,
    telefone VARCHAR(128) NOT NULL,
    PRIMARY KEY (id)
);